/**
 * Canonical permission codes. Add to this list as each CRM module grows —
 * this file plus the seed script is the single source of truth for what a
 * role can be granted. Route files reference these strings directly via
 * requirePermission(...) rather than importing this file, to keep modules
 * decoupled; this list exists for seeding and documentation.
 */
const PERMISSIONS = {
  USERS_CREATE: 'users:create',

  CONTACTS_READ: 'contacts:read',
  CONTACTS_CREATE: 'contacts:create',
  CONTACTS_UPDATE: 'contacts:update',

  COMPANIES_READ: 'companies:read',
  COMPANIES_CREATE: 'companies:create',
  COMPANIES_UPDATE: 'companies:update',

  PIPELINE_READ: 'pipeline:read',
  PIPELINE_MANAGE: 'pipeline:manage',

  DEALS_READ: 'deals:read',
  DEALS_CREATE: 'deals:create',
  DEALS_UPDATE: 'deals:update',

  ACTIVITIES_READ: 'activities:read',
  ACTIVITIES_CREATE: 'activities:create',
  ACTIVITIES_UPDATE: 'activities:update',

  SEGMENTS_READ: 'segments:read',
  SEGMENTS_CREATE: 'segments:create',
  SEGMENTS_UPDATE: 'segments:update',

  CAMPAIGNS_READ: 'campaigns:read',
  CAMPAIGNS_CREATE: 'campaigns:create',
  CAMPAIGNS_UPDATE: 'campaigns:update',
  CAMPAIGNS_SEND: 'campaigns:send',

  REPORTS_READ: 'reports:read',

  PROPERTY_MANAGE: 'property:manage',

  AUDIT_READ: 'audit:read',

  NOTIFICATIONS_READ: 'notifications:read',

  RETENTION_READ: 'retention:read',
  RETENTION_MANAGE: 'retention:manage',
};

const ROLE_PERMISSION_DEFAULTS = {
  super_admin: Object.values(PERMISSIONS),
  property_manager: [
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONTACTS_CREATE,
    PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.COMPANIES_CREATE,
    PERMISSIONS.COMPANIES_UPDATE,
    PERMISSIONS.PIPELINE_READ,
    PERMISSIONS.PIPELINE_MANAGE,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.DEALS_CREATE,
    PERMISSIONS.DEALS_UPDATE,
    PERMISSIONS.ACTIVITIES_READ,
    PERMISSIONS.ACTIVITIES_CREATE,
    PERMISSIONS.ACTIVITIES_UPDATE,
    PERMISSIONS.SEGMENTS_READ,
    PERMISSIONS.SEGMENTS_CREATE,
    PERMISSIONS.SEGMENTS_UPDATE,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.CAMPAIGNS_CREATE,
    PERMISSIONS.CAMPAIGNS_UPDATE,
    PERMISSIONS.CAMPAIGNS_SEND,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.PROPERTY_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.RETENTION_READ,
    PERMISSIONS.RETENTION_MANAGE,
  ],
  sales_agent: [
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONTACTS_CREATE,
    PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.COMPANIES_CREATE,
    PERMISSIONS.COMPANIES_UPDATE,
    PERMISSIONS.PIPELINE_READ,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.DEALS_CREATE,
    PERMISSIONS.DEALS_UPDATE,
    PERMISSIONS.ACTIVITIES_READ,
    PERMISSIONS.ACTIVITIES_CREATE,
    PERMISSIONS.ACTIVITIES_UPDATE,
    PERMISSIONS.SEGMENTS_READ,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  auditor: [
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.PIPELINE_READ,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.ACTIVITIES_READ,
    PERMISSIONS.SEGMENTS_READ,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.RETENTION_READ,
  ],
};

module.exports = { PERMISSIONS, ROLE_PERMISSION_DEFAULTS };
